name: Update Profile Card

on:
  schedule:
    - cron: "0 0 * * *"   # daily at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests jinja2

      - name: Run update script
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python update_stats.py

      - name: Update README timestamp
        run: |
          date_str=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          sed -i "s|Last updated:.*|Last updated: $date_str|g" README.md

      - name: Commit & Push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add update_stats.svg README.md
          git diff --staged --quiet || git commit -m "Update profile stats"
          git push
